### ISSUE TITLE
CK editor Edit link error

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#100]
OC 4.3.0
I have a DNN 08.00.04 installation where editing or editing links in the CKeditor stopped working

When I try to open the CKEditors Link dialog the screen turns grey and nothing happens.
The browser console shows this error:

TypeError: dnnpagesLang is undefined

Referring to:
  {
                    id: 'linkType',
                    type: 'select',
                    label: linkLang.type,
                    'default': 'url',
                    items: [
                        [linkLang.toUrl, 'url'],
                        [dnnpagesLang.toPage, 'localPage'],
                        [linkLang.toAnchor, 'anchor'],
                        [linkLang.toEmail, 'email'],
                        [linkLang.toPhone, 'tel']
                    ],
                    onChange: linkTypeChanged,
                    setup: function (data) {
                        this.setValue(data.type || 'url');
                    },
                    commit: function (data) {
                        data.type = this.getValue();
                    }
                },

in link.js

The page has one language active and only a few pages.

------------------

I found that in the options file:

"Text": {
							"type":"ckeditor",
							"configset":"basic",
							"ckeditor":{
								"extraAllowedContent": "iframe embed video table tr th td div span(*);"
							}
						},

The configset element causes this.

**Comment by Timo-Breumelhof** [comment]
I tried this on another install and there I cannot reproduce it.
I do see these errors on both installations:

[CKEDITOR] Error code: editor-plugin-conflict. 
Object { plugin: "image", replacedWith: "easyimage" }
ckeditor.js:21:171
[CKEDITOR] For more information about this error go to https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#editor-plugin-conflict

**Comment by sachatrauwaen** [comment]
fixed in v 4.4
