### ISSUE TITLE
Template css and js not loading

### ISSUE THREAD

**Issue by cklenk** [sachatrauwaen/OpenContent#102]
Hello, I noticed if I have composite files turn on and minify css and js that the template.css and template.js does not load in an open content template. I'm using version 4.3 on DNN version 9.4.1. We have noticed it not work on older versions of DNN as well. As soon as we turn it off, all is well again.

Thanks
-Cameron

**Comment by sachatrauwaen** [comment]
You can try to increment version of client resource management.
In DNN Settings, servers, server settings, performance.

And look if they are loaded correctely after that

**Comment by cklenk** [comment]
Unfortunately that doesn't seem to fix it either.

**Comment by Timo-Breumelhof** [comment]
I think that if your template is named "mytemplate" (either in the manifest or the name of the template file itself) you need to name the CSS and JS files accordingly.

**Comment by Timo-Breumelhof** [comment]
Did you find a fix for this?
