### ISSUE TITLE
Image browser in CKEditor missing after updating from 3.x to 4.x

### ISSUE THREAD

**Issue by bdukes** [sachatrauwaen/OpenContent#103]
After upgrading OpenContent from 3.5.2 to 4.3, we're seeing that the CKEditor fields are working a little bit differently than previously.  The first issue had to do with the links plugin not working, but following @Timo-Breumelhof's note on #100 was able to find a fix/workaround for that. 

The other major issue is that the images plugin isn't displaying.  I see in the release notes that the Easy Image plugin was added, and if I switch out the config to use the _full_ config set then I see that option (I can also drag an image into the CKEditor without changing any of the config, and it'll get uploaded).  However, that only handles image uploads, and not browsing already uploaded images (and doesn't appear to support editing images already in the HTML).

Here's the configuration for the field:
```
          "Content": {
            "type": "ckeditor",
            "configset":"basic",
            "ckeditor":{
              "toolbar": [
                { "name": "basicstyles", "items": [ "Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "-", "RemoveFormat" ] },
                { "name": "insert", "items": [ "Image", "Table", "HorizontalRule", "SpecialChar", "Iframe" ] },
                { "name": "links", "items": [ "Link", "Unlink" ] },
                { "name": "paragraph", "items": [ "NumberedList", "BulletedList", "-", "Outdent", "Indent", "-", "Blockquote", "CreateDiv", "-", "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock" ] },
                { "name": "editing", "items": [ "Find", "Replace", "-", "SelectAll" ] },
                { "name": "tools", "items": [ "Maximize" ] },
                "/",
                { "name": "clipboard", "items": [ "Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "-", "Undo", "Redo" ] },
                { "name": "colors", "items": [ "TextColor", "BGColor" ] },
                { "name": "styles", "items": [ "Styles", "Format", "Font", "FontSize" ] },
                { "name": "document", "items": [ "Source"] }
              ],
              "filebrowserBrowseUrl" : "/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx?mode=Default&Type=Link",
              "filebrowserImageBrowseUrl" : "/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx?Type=Image&mode=Default",
              "filebrowserImageUploadUrl" : "/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx?Command=ImageUpload&mode=Default"
            }
          }
```

However, when loading the editor, I get this error in the console:
>[CKEDITOR] Error code: editor-plugin-conflict. `{ plugin: "image", replacedWith: "easyimage" }`
>[CKEDITOR] For more information about this error go to https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#editor-plugin-conflict

Was the old image plugin removed?  Or is there a different configuration I can use to reintroduce it?

**Comment by bdukes** [comment]
It looks like in cc9a6bf678486d313a185ab5751d2673a2046f3d `image` was added to the `removePlugins` config.  Is there any way to undo or override that?  Or a different approach I should take to making images manageable?  Thanks!

**Comment by Timo-Breumelhof** [comment]
@bdukes , the Image browser never worked in Open Content AFAIK because it's not using DNN's implementation (as that's based on an ASPX) but calls the js directly.
To "fix" this, the "easyimage" plugin was implemented and AFAIK, OC comes with it's own CKEditor now as it requires CK4.
Did Browse image work for you in previous version of OC? did you implement your own browser plugin ?

**Comment by b-creative** [comment]
You can always use the Summernote editor, which decodes your image into base64 images, but if you use many images, that's probably not an option.

**Comment by bdukes** [comment]
I _think_ that by using the configuration above, where we point to the file browser from the CKEditor Provider, allowed the file browsing to work.

I tried adding `"removePlugins":"elementspath,link"` to override the default and allow `image` to load again, but it didn't make a difference.

**Comment by bdukes** [comment]
I figured out the issue, I needed to _remove_ `easyimage` so that it didn't conflict with the `image` plugin, so I added `"removePlugins":"elementspath,link,easyimage"` and the image browser started working again.

**Comment by Timo-Breumelhof** [comment]
> 
> 
> I _think_ that by using the configuration above, where we point to the file browser from the CKEditor Provider, allowed the file browsing to work.
> 
> I tried adding `"removePlugins":"elementspath,link"` to override the default and allow `image` to load again, but it didn't make a difference.

Hmm, cool I never realized that would be possible (and I missed it in your issue), did you @sachatrauwaen ?

**Comment by b-creative** [comment]
What Timo says....
