### ISSUE TITLE
Getting Failed Error When Trying to OpenContent Upload Extension

### ISSUE THREAD

**Issue by CheriEpps** [sachatrauwaen/OpenContent#124]
I am the site administrator and able to upload other extensions. Was trying to update the OpenContent Extension and received the following message. I deleted the old extension thinking that would help, but to no avail.  Please assist.

**StartJob Starting Installation

Info Starting Installation - OpenContent

Info Starting Installation - Script

Info Begin Sql execution

Info Creating backup of previous version - Providers\DataProviders\SqlDataProvider\00.00.01.SqlDataProvider

Failure ExceptionSystem.UnauthorizedAccessException: Access to 'D:\media\DesktopModules\OpenContent\Providers\DataProviders\SqlDataProvider\00.00.01.SqlDataProvider' denied. ---> System.ComponentModel.Win32Exception: Access is denied --- End of inner exception stack trace --- at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode) at SchwabenCode.QuickIO.Internal.InternalQuickIO.SetAttributes(QuickIOPathInfo pathInfo, FileAttributes attributes) at DotNetNuke.Common.Utilities.FileSystemUtils.CopyFile(String sourceFileName, String destFileName) at DotNetNuke.Common.Utilities.Internal.RetryableAction.TryIt() at DotNetNuke.Services.Installer.Util.CopyFile(InstallFile installFile, String basePath, Logger log) at DotNetNuke.Services.Installer.Installers.FileInstaller.InstallFile(InstallFile insFile)

Info Finished Sql execution

Failure Installation Failed - Script

Info Installation Failed - OpenContent

Info Deleted temporary install folder

EndJob Installation Failed**

**Comment by Timo-Breumelhof** [comment]
Strange, I install Open Content a lot and I have never seen this issue.
"Access is denied" looks like a NTFS rights issue in disk.
Do you have any more information like DNN version, hosting environment etc.?
