### ISSUE TITLE
Additional data edit link

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#128]
with {{Context.EditUrl}} you can add an edit item link to your template.
{{AddtionalData.name.EditUrl}} would be a nice addition, so you can provide a link to editing categories for instance.. :-)

**Comment by sachatrauwaen** [comment]
Implemented exemple : <a href="{{AdditionalData.Context.Categories.EditUrl}}">Edit Categories</a>

**Comment by schotman** [comment]
works as expected

**Comment by Timo-Breumelhof** [comment]
Fixed in 04.06.00
