### ISSUE TITLE
Delete associated file(s) when item is deleted

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#132]
Use case:
A list of employees with Photo and CV.PDF

When you remove a user from that list, it would good if the photo and CV could also be removed as an option as otherwise they keep getting indexed by google.

Suggestion:
- Add the option to create a folder per item for file storage. 
- Add option to manifest to delete files that are store in a separate item folder.

**Comment by sachatrauwaen** [comment]
new option in manifest root : DeleteFiles

**Comment by Timo-Breumelhof** [comment]
tested see video in email

**Comment by sachatrauwaen** [comment]
Issue on create new item  because no item id is available.
We will switch to guid foloder for images .

**Comment by schotman** [comment]
tested with articles template, changed the manifest with setting, dnn981, latest dev build
I get a internal server error, no additional info.
Item is deleted, images are still there, there is no folder created when adding articles

**Comment by schotman** [comment]
works for main images of type image and image-x

**Comment by Timo-Breumelhof** [comment]
Fixed in 04.06.00
