### ISSUE TITLE
Template folder in Json / data

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#133]
Use case:

If no image is selected on imagex I would like to show a fallback image from the OC template folder.
For that you would need to know the path to the selected template.

{{context.TemplatePath}}

**Comment by Timo-Breumelhof** [comment]
For loading a fallback image

**Comment by sachatrauwaen** [comment]
resolved in version 4.6

**Comment by Timo-Breumelhof** [comment]
getest, ok

**Comment by Timo-Breumelhof** [comment]
Fixed in 04.06.00
