### ISSUE TITLE
Prevent showing module action "add item" and "edit addional data"

### ISSUE THREAD

**Issue by schotman** [sachatrauwaen/OpenContent#135]
In a satelite (e.g. "latest") module you sometimes don't want editors to add items (and/or manage aditional data) because it can confusing esspecially when there is an active filter on the satelite module.

This could e.g. be done by having an option in the manifest to hide the add button (and hide additional data)

![image](https://user-images.githubusercontent.com/2582737/98938603-704c6700-24e8-11eb-8a8e-efb88232b382.png)

**Comment by robsiera** [comment]
Suddenly not having those buttons anymore can be confusing too, no? Can we keep the buttons and add a message/tooltip with a hyperlink to the correct page for these operations?

**Comment by Timo-Breumelhof** [comment]
The idea is to have this as an option for a template not by default.
When you have a template with filtered lists and a users adds an item and it disappears which can be very confusing.
Also users have removed categories from that list because they didn't "need them there"..

**Comment by robsiera** [comment]
I understand the need for disabling. But if possible I would go for disabling with extra 'redirect' message.

**Comment by Timo-Breumelhof** [comment]
Ok, something like 
{{#unless Context.AddContent}}Go to <a>this page to edit</a>{{/unless}}
 for use in the template?
(I tend to do that more and more, show instructions for editors from within the template and it seem to work out quite well)

**Comment by sachatrauwaen** [comment]
I added disableEdit on template template level (second level) in manifest.

**Comment by schotman** [comment]
Tested on new build and it works as expected.
