### ISSUE TITLE
Improve speed ImageX when using an image folder with a lot of images

### ISSUE THREAD

**Issue by schotman** [sachatrauwaen/OpenContent#137]
With an image folder with more than 200 images it takes about 4 seconds to have a usable edit dialog.

**Comment by Timo-Breumelhof** [comment]
Core handler gebruiken

**Comment by sachatrauwaen** [comment]
if ImageProcessor exist we use it
else if DnnImageHandler exist we use it
else full image

**Comment by Timo-Breumelhof** [comment]
I tested this with 9.8.0 and the images are not shown using the DNN image handler:

![image](https://user-images.githubusercontent.com/8999382/101749538-29916300-3ace-11eb-83dc-f325b3f52648.png)

Path: /DnnImageHandler.ashx?mode=file&file=/Portals/opencontent-demo-templates/Images/OpenContent/Links-Block/original/600_fp.jpg&resizemode=Crop&w=40&h=40

**Comment by schotman** [comment]
No speed improvement seen, images do show up in the dropdown. App-data image processor cache directory does not contain thumbnails

**Comment by schotman** [comment]
no improvement in speed on repeated edit, both with and without image processor. 
Takes a number of seconds when image directory has > 100 images

**Comment by Timo-Breumelhof** [comment]
Fixed in 04.06.00
