### ISSUE TITLE
FormBuilder - ImageX - inconsistency in UI

### ISSUE THREAD

**Issue by robsiera** [sachatrauwaen/OpenContent#139]
When creating a ImageX field in the FormBuilder and enabling "Show Overwrite" and "Overwrite" the "Overwrite" checkbox is not rendered correctly. Under these conditions the rendered checkbox should be set to "enabled" by default. Instead it is always rendered as disabled.
![image](https://user-images.githubusercontent.com/5709726/99867062-98a62680-2bb6-11eb-8796-949fddbc88da.png)

**Comment by sachatrauwaen** [comment]
will befixed in v4.6
