### ISSUE TITLE
HTML Stripping?

### ISSUE THREAD

**Issue by MaiklT** [sachatrauwaen/OpenContent#140]
I configured a template to use ckeditor for a rich text field. This works fine so far.

When I enter some code like this in the source code mode:

    <ul class="fa-ul">
       <li><i class="fas fa-user fa-fw mr-3"></i><a href="#">Go to somewhere</a></li>
    </ul>

it saves the HTML as expected, but when I reopen the module to edit it, the code looks like

    <ul>
       <li><a href="#">Go to somewhere</a></li>
    </ul>

My CKEditor configuration has allowedContent=true, and the code is not stripped when I use a "normal" HTML/Text module. Again, it saves correctly (the entered HTML is also in the OpenContent_Items.Json field - the line looks like:

    "Description": "<ul class=\"fa-ul\">\n   <li><i class=\"fas fa-user fa-fw mr-3\"></i><a href=\"#\" rel=\"nofollow\">Vereinfachen - Vertrauen - Gestalten</a></li>\n</ul>\n"

But the HTML is stripped when loading it for editing.

Any ideas?

**Comment by Timo-Breumelhof** [comment]
Did you change the CKeditor configuration in DNN or in Open Content?
Open Content currently loads it's own editor because the core version is an older version, so you should add allowedContent in the Open Content CKEditor configuration.

**Comment by Timo-Breumelhof** [comment]
example options file:

```
"CKEditor3": {
			"type": "ckeditor",
			"ckeditor":{
					"extraAllowedContent": "table tr th td div span(*);"
				}
		}
```

**Comment by Timo-Breumelhof** [comment]
FYI, @skamphuis is preparing a PR to upgrade the core editor to the latest CK4 version

**Comment by MaiklT** [comment]
Thanks for the answer, @Timo-Breumelhof. I did the configuration in the DNN HTML Provider, as I did not realize that OpenContent uses it's own wrapper for it.

In my options.js (in the template directory, /Portals/0/OpenContent/Templates/TemplateName/options.js) I did the following now:

    [...]
          "Description": {
            "type": "ckeditor",
            "ckeditor": { "extraAllowedContent": "*[*]" },
            "configset": "full"
          },
    [...]

(and then I restarted the app pool just to be sure that there is no caching issue)

That did not change anything in the behaviour - the whole HTML is still stripped out. Are you referring to another options file?

**Comment by Timo-Breumelhof** [comment]
Hmm, right I just tested this:

```
"CKEditor3a": {
			"type": "ckeditor",
			"ckeditor":{
					"allowedContent" : true
				}
		}

```
And it only removes the empty <i>.
That's another issue, discussed here: https://stackoverflow.com/questions/18250404/ckeditor-strips-i-tag
I'm not sure if you can manipulate the dtd from the config file though and I guess the reason this work in the core editor is that it's an older version.

BTW, for direct input of HTML I generally just use a textarea field, not the ckeditor.
Or in this case a separate text and icon field.

**Comment by Timo-Breumelhof** [comment]
I did find some kind of hack around this, but it only survives one switch from source to html:

<ul class="fa-ul" >
   <li><i class="fas fa-user fa-fw mr-3" data-cke-survive="1"></i><a href="#">Go to somewhere</a></li>
</ul>

**Comment by MaiklT** [comment]
Thank you @Timo-Breumelhof, I did find this thread as well - and I also tried

    "allowedContent": true

The interesting thing is that it allows to store it, but when you re-enter the edit mode it's gone. The problem is, it could look like this as well:

    <ul class="fa-ul">
       <li><i class="far fa-newspaper fa-fw mr-3"></i><a href="#">Link 1</a></li>
       <li><i class="fas fa-circle-notch fa-fw mr-3"></i><a href="#">Link 2</a></li>
       <li><i class="far fa-newspaper fa-fw mr-3"></i><a href="#">Link 3</a></li>
       <li><i class="fas fa-exclamation-triangle fa-fw mr-3"></i><a href="#">Link 4</a></li>
    </ul>

And it can look like this (which works without problems):

    <p>
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore
        et <a href="somesite" target="_blank">dolore magna</a> aliquyam erat, sed diam voluptua. At vero eos et
        accusam et justo duo dolores et ea rebum.<br />
        Stet clita kasd gubergren, no sea <a href="another_Page">takimata</a> sanctus est Lorem ipsum dolor sit amet.
    </p>

etc. etc.

It's the backside of a flip card, and the (kind of) content is different for different cards.

The textarea could be a workaround, but is not suitable for normal users.

**Comment by Timo-Breumelhof** [comment]
IMO entering HTML is bad for normal users also and prone to being messed up.
You could also add a type selector at the top and using dependencies in alpaca show and hide fields.

**Comment by MaiklT** [comment]
OK, the textarea solves it (more or less).
