### ISSUE TITLE
Template data not written in console

### ISSUE THREAD

**Issue by b-creative** [sachatrauwaen/OpenContent#144]
I use OC 4.5.0 and DNN 9.7.2

There's no detailed data written in the console.

**Comment by sachatrauwaen** [comment]
Do you have activate logging in the glabal settings ?

**Comment by b-creative** [comment]
Yes

**Comment by b-creative** [comment]
can someone reproduce?

**Comment by Timo-Breumelhof** [comment]
Is this a handlebars template? As with a Razor template there is no logging in the console..

**Comment by b-creative** [comment]
This is the Articles template

**Comment by b-creative** [comment]
Mmm, somehow I filtered the console output, sorry... all works fine.
