### ISSUE TITLE
AutoEditMode Breaks Persona Bar Functionality

### ISSUE THREAD

**Issue by mikesmeltzer** [sachatrauwaen/OpenContent#145]
The AutoEditMode function forces the Persona Bar to think it is in Edit mode even though the user wants to be in View mode. This breaks the Persona Bar Edit pencil functionality by not letting the PersonaBar refresh the page after the user has clicked the pencil. Then are instead forced to press refresh on their browser to get into Edit mode.

**Comment by Timo-Breumelhof** [comment]
We are seeing this on one installation too, not sure why we don't see it on anther one that has the same OC version though..

**Comment by mikesmeltzer** [comment]
@Timo-Breumelhof it all depends on the site's settings. Check the 'ControlPanelMode' setting in PortalSettings. If that's set to EDIT then you'll experience the issue I describe here. Open Content is reading this setting and the subsequent logic in OpenContent is causing the issue.

**Comment by Timo-Breumelhof** [comment]
> 
> 
> @Timo-Breumelhof it all depends on the site's settings. Check the 'ControlPanelMode' setting in PortalSettings. If that's set to EDIT then you'll experience the issue I describe here. Open Content is reading this setting and the subsequent logic in OpenContent is causing the issue.

OK, thanks that at least fixes it for now..

**Comment by Timo-Breumelhof** [comment]
Should be fixed in v 04.06.00

**Comment by Timo-Breumelhof** [comment]
Fixed in 04.06.00

**Comment by Timo-Breumelhof** [comment]
Hmm, I just had the same issue in Evoq 9.8.0, with OC 4.6.0 not sure if it's really fixed..
