### ISSUE TITLE
Ability to assign a different skin for detail pages

### ISSUE THREAD

**Issue by robert-m** [sachatrauwaen/OpenContent#148]
Hi guys!
Is there any way to assign or serve a different skin for the details page?

Example: The **main** template uses the skin thats already assigned via the Page Settings (eg. "**videos.ascx**") but once a user clicks to view the **detail.hbs** page it serves a different skin (eg. "**video-details.ascx**") 

```
 "templates": {
    "Main": {
      "type": "multiple",
      "title": "Videos",
      "main": {
        "template": "template.hbs"
      },
      "detail": {
        "template": "detail.hbs",
        "skin": "video-details.ascx"
      }
    }
  }
```

**Comment by Timo-Breumelhof** [comment]
How I handle  this is by creating a details page and place the module on that page too.
