### ISSUE TITLE
Cropped image size much bigger than original

### ISSUE THREAD

**Issue by cklenk** [sachatrauwaen/OpenContent#151]
Hello,

We are using open content 4.5 on dnn 9.8.1. We have a template using a imagex type. Here is the definition.

`"Image": {
						"title": "Image",
						"label": "Image",
						"type": "imagex",
						"width": 800,
						"height": 600,
						"helper": "First select an image and then be sure to click Crop.",
						"showCropper": true,
						"saveCropFile": true,
						"overwrite": false
					}`

I'v noticed that the cropped images are much bigger than the original files uploaded. One example is the uploaded file is 61.7 KB. We set the crop size to 800x600. And that file is 1.9 MB.

Original files
![image](https://user-images.githubusercontent.com/12185742/108095044-71dc7c80-704d-11eb-80e3-3326fcfc6f3e.png)

Cropped files
![image](https://user-images.githubusercontent.com/12185742/108095073-7acd4e00-704d-11eb-817d-918e333a4990.png)

Any idea what is going on?

Thanks
-Cameron

**Comment by Timo-Breumelhof** [comment]
What are the pixel sizes of the original images? This could be due to the jpeg compression being lower on the original images if they are also quite low in pixels.

**Comment by cklenk** [comment]
Here is some comparisons between the original and cropped
![image](https://user-images.githubusercontent.com/12185742/108387381-88b0d980-71db-11eb-8dd2-bfbddee62b82.png)

**Comment by b-creative** [comment]
Yeah, it's 96 dpi, and not the expected web format 72 dpi.

**Comment by Timo-Breumelhof** [comment]
@b-creative DPI does not really matter on the Web. A browser will just show Pixels

**Comment by Timo-Breumelhof** [comment]
@cklenk that's strange. I just checked some of my cropped files and they are considerably smaller.
Can you reproduce this with the attached image?
![pexels-photo-160207](https://user-images.githubusercontent.com/8999382/108416433-fa664300-722e-11eb-8ec7-59dee4944b75.jpg)

**Comment by b-creative** [comment]
> @b-creative DPI does not really matter on the Web. A browser will just show Pixels

Ofcourse, but it effects file size.

**Comment by Timo-Breumelhof** [comment]
> 
> 
> > @b-creative DPI does not really matter on the Web. A browser will just show Pixels
> 
> Ofcourse, but it effects file size.

AFAIK 100 x 100px image @72 DPI is just a big as the same image @ 1000 dpi.

**Comment by cklenk** [comment]
@Timo-Breumelhof we re-exported the images at 72 dpi and ran them through the image cropper again. The file sizes did not explode this time. So I think we fund the culprit. Thank you for the help everyone!
![image](https://user-images.githubusercontent.com/12185742/108548503-e9164880-72b9-11eb-9d1e-7c16f0caa556.png)
