### ISSUE TITLE
Fast Add Issue

### ISSUE THREAD

**Issue by cklenk** [sachatrauwaen/OpenContent#153]
Hello. We were trying to run the fast add module here https://opencontent.readme.io/changelog/dnn-9-fast-add-modules-to-pages#how-to-install on dnn 9.9. It does not seem to work on 9.9. You click on the fast add icons and nothing happens. Here are some console errors: 
![image](https://user-images.githubusercontent.com/12185742/110532088-65968d00-80ea-11eb-9810-c49591c9e262.png)
And yes this happens on the default Xcillion skin too.

Thanks 
-Cameron

**Comment by Timo-Breumelhof** [comment]
As this is tapping into the Persona Bar JS, it might be that changes to the PB broke this.

**Comment by Timo-Breumelhof** [comment]
There's a new version for DNN 9 here: https://github.com/sachatrauwaen/OpenContent-Templates2/tree/main/Dnn9FastAddModule
