### ISSUE TITLE
Idea: Visible lock in Formbuilder

### ISSUE THREAD

**Issue by b-creative** [sachatrauwaen/OpenContent#156]
Many of my clients, as do I, like to work with the Formbuilder. The problem is sometimes that some  changes can only be done directly via Options.json and one overwrites everything. 

Perhaps a visible lock icon that would automatically appear next to the Formbuilder link in the edit menu is an idea? 

Or making sure that everything can be changed from the Formbuilder would be better ofcourse😄

**Comment by Timo-Breumelhof** [comment]
Sacha is working on a new builder that will not have this issue.

**Comment by b-creative** [comment]
Great!
