### ISSUE TITLE
Ability to make all content searchable

### ISSUE THREAD

**Issue by b-creative** [sachatrauwaen/OpenContent#162]
It's great to be able to add dnnsearch=true in the manifest file of the articles module. But it would be great if I can do that also with for example the HandlebarsStarter template! Or is it already possible?

**Comment by Timo-Breumelhof** [comment]
You can add that to any Template AFAIK

**Comment by b-creative** [comment]
So just add a manifest.json file?

**Comment by Timo-Breumelhof** [comment]
yes, with that setting

**Comment by b-creative** [comment]
Is there a list of settings that only work with certain templates/works with all templates?

**Comment by b-creative** [comment]
This is now my new manifest.json:

`{`
`    "editWitoutPostback": true,`
`    "editRole": "",`
`    "index": true,`
`    "disableEdit": false,`
`    "templates": {`
`        "template": {`
`            "type": "single",`
`            "title": "Mediablokken",`
`            "main": {`
`                "template": "template.hbs",`
`                "schemaInTemplate": true,`
`                "optionsInTemplate": true,`
`                "additionalDataInTemplate": true,`
`                "dnnsearch": true,`
`                "dnnSearchTitle": "{{Titel}}",`
`                "dnnSearchDescription": "{{Details}}",`
`                "dnnSearchText": "{{Details}}"`
`            }`
`        }`
`    }`
`}`

What do you think? I don't know for example what index:true does...

**Comment by Timo-Breumelhof** [comment]
> 
> 
> Is there a list of settings that only work with certain templates/works with all templates?

OC is not built that way, in general everything works in all templates, although there can be a difference between single and multi item templates

**Comment by Timo-Breumelhof** [comment]
Looks good to me. 
index:true = for Lucene, the internal OC search engine used with jplist (example the Articles template)

**Comment by b-creative** [comment]
There's no menu item "Filter Settings" created though...

**Comment by b-creative** [comment]
Probably because it's a single-item-template? I hope the DNN search indexing works!

**Comment by Timo-Breumelhof** [comment]
Correct, internal Lucene indexing is only for multi item templates

**Comment by b-creative** [comment]
? I'm confused now. I thought Lucene indexing ís for DNN search?

**Comment by Timo-Breumelhof** [comment]
DNN uses lucene, but OC also uses it for internal indexing to filter items server side (when requested through webapi).\
So 2 separate systems, for 2 different use cases

**Comment by b-creative** [comment]
1. How can I doublecheck if it get's indexed correctly or not? 
2. DNN search results do not return the desired results. When it concerns only content of Columns (fieldtype array), do I have to put it like this?

`"dnnSearchTitle": "{{Columns.Titel}}",`
`"dnnSearchDescription": "{{Columns.Details}}",`
`"dnnSearchText": "{{Columns.Details}}"`

**Comment by b-creative** [comment]
Can you please reopen this issue? Single item templates do not seem to appear in DNN search results...

**Comment by Timo-Breumelhof** [comment]
hmm, ok I think they should be: https://opencontent.readme.io/discuss/592bd7a742c5800f00422def @sachatrauwaen ?

**Comment by Timo-Breumelhof** [comment]
> 
> 
> Can you please reopen this issue? Single item templates do not seem to appear in DNN search results...

FYI, I just checked on of my single templates and it works as expected.
Manifest:
{
    "editWitoutPostback": true,
    "index": true,
	 "templates": {
	    "template": {
            "type": "single",
            "main": {
                "template": "template.cshtml",
				"clientSideData": false,
				"dnnsearch": true,
				"dnnSearchTitle": "{{ModuleTitle}}",
                 "dnnSearchDescription": "{{Text}}",
                 "dnnSearchText": "{{Text}}"
            }
        }
    }
}

**Comment by b-creative** [comment]
In which version did you check?

**Comment by Timo-Breumelhof** [comment]
Ok, for another project we are debugging the Search implementation (to add something) and it seems that the results I got are not from the OC module crawled by DNN Search it seems, so I think you do have a point (also in multi-item templates).. When we know more we will post here. @skamphuis @sachatrauwaen @robsiera

**Comment by Timo-Breumelhof** [comment]
@b-creative  Looks like this is an issue for ML fields, are your the fields you are indexing ML fields?

**Comment by Timo-Breumelhof** [comment]
@b-creative this is what we found, please test these are the same circumstances as yours.
https://github.com/sachatrauwaen/OpenContent/issues/168

**Comment by b-creative** [comment]
In my case it does not concern ML fields or multi-language website. The multiple-item-template-items get indexed correctly though. Only the content using single-item-template (the basis is the HandlebarsStarter template with an added manifest.json that looks like this:

**Comment by Timo-Breumelhof** [comment]
Did you try to delete the DNN search index files?

**Comment by b-creative** [comment]
> Did you try to delete the DNN search index files?

no, which ones? All in \App_Data\Search?

**Comment by Timo-Breumelhof** [comment]
yes

**Comment by b-creative** [comment]
just did... first recycled tha application, then removed all from this folder, did a reindex... same results: no single-item-template-content results

**Comment by skamphuis** [comment]
Other than the issue with ML field in a single language website, I didn't run into issues with dnn search.

Could you attach (or email, you got my address) your template?

**Comment by skamphuis** [comment]
@b-creative I tested your template with both the latest release (4.6.0) and the current develop branch (which includes #169 and #170 ) but indexing the content seems to work just fine for both versions. The result shows up in both the search dropdown and the search results page.

**Comment by b-creative** [comment]
Can it be the DNN-version than? As you know/have seen, I’ve tried pretty much everything…

**Comment by b-creative** [comment]
Maybe a valid variable: I have also installed the [OpenContent_OpenUrlRewriter](https://github.com/sachatrauwaen/OpenContent_OpenUrlRewriter)

**Comment by skamphuis** [comment]
> 
> 
> Thanks! Can it be the DNN-version than? As you know/have seen, I’ve tried pretty much everything…

I tried on DNN 9.9.1,

**Comment by skamphuis** [comment]
> 
> 
> Maybe a valid variable: I have also installed the [OpenContent_OpenUrlRewriter](https://github.com/sachatrauwaen/OpenContent_OpenUrlRewriter)

I don't see how that could be relevant, sorry.
