### ISSUE TITLE
Handlebars helper "Contains" inconsitancy

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#165]
The documentation of this helper https://opencontent.readme.io/docs/tokens shows:

![image](https://user-images.githubusercontent.com/8999382/118624894-d97ba280-b7c9-11eb-8f45-393b263368ad.png)

But that did not work the way I expected.

I found out it works like this: {{#contains "string" field}}

See also:
https://github.com/sachatrauwaen/OpenContent/blob/a3dadd8cc7414ad622ff6bc3e0f0cd9aed41ae3a/OpenContent/Components/Handlebars/HandlebarsEngine.cs#L1118

IMO that's not logical, but I guess it's a breaking change if we fix it according to the documentation?

@hismightiness @sachatrauwaen

**Comment by b-creative** [comment]
I have also used it like this:
`{{#contains @index 1}}`
`{{/contains}}`

**Comment by Timo-Breumelhof** [comment]
I think that's because index = 1 so the comparison is 1 contains 1 and thus the order does not matter

**Comment by hismightiness** [comment]
In my opinion, this is a necessary breaking change if all of the other implementations work differently.

**Comment by sachatrauwaen** [comment]
Fixed in v4.7
