### ISSUE TITLE
Open Content on DNN9

### ISSUE THREAD

**Issue by ransems** [sachatrauwaen/OpenContent#18]
It appears the module does not work with the new interface for module selection and module placement in DNN9. Can anyone confirm they are also having issues?  
The issue being when you select the module from the list to add to a page, the module hover/move render is all messed up.  cannot grab it anywhere, the module HTML is spilling down over the module interface. Etc.
I will try with a different skin, but i am using the default DNN9 skin too. Ill revert back to DNN8, but just a heads up.
![image](https://cloud.githubusercontent.com/assets/3457320/22626119/b30ec88e-eb7c-11e6-8eb0-f3fe3a7afe21.png)

**Comment by sachatrauwaen** [comment]
I have no issue with in DNN9
