### ISSUE TITLE
Default install shows unstyled <ul> for paging and sorting

### ISSUE THREAD

**Issue by RichardHowells** [sachatrauwaen/OpenContent#183]
Hi - I installed v.latest (4.07.00) onto a test version of my site (dnn 9.4.4).

The ul's for pagination and sorting look to be displaying unstyled.

![image](https://user-images.githubusercontent.com/6627531/143773937-6bbc8d5a-c62b-48c9-9c65-c6f539ea1a67.png)

I can see from developer tools that the ul carries role='menu'.  This is not something I am familiar with, but makes me wonder if there is some dependency on bootstrap, or a specific bootstrap version that is missing from my site.

Is there something I need to add?  My site's skin is non-bootstrap.

Thank you to all the contributors for what looks like an amazing piece of work.

**Comment by sachatrauwaen** [comment]
Hi, the articles templates need bootstrap 3.
If you want you can also adapt the template by yourself to use other css frameworks.

**Comment by Timo-Breumelhof** [comment]
BTW, it works with Bootstrap 4 too

**Comment by RichardHowells** [comment]
Thank you for the information.  I'm going to try a bootstrap based skin.  It's time for a change.
