### ISSUE TITLE
Image Cropper treats .Jpeg files as BMP

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#184]
When using the option to generate a cropped image using the imageX field, when the file has an .JPEG (so not .JPG) extension, the cropped files are saved as a BMP with .JPEG extension.
Also they are larger in size (MB's) than the JPEG they were intended to be.

The issue is this check:
https://github.com/sachatrauwaen/OpenContent/blob/e9de4aecf5e974df8b3bac41d26555080b02e249/OpenContent/Components/DnnEntitiesAPIController.cs#L529

**Comment by Timo-Breumelhof** [comment]
Also: https://github.com/sachatrauwaen/OpenContent/blob/e9de4aecf5e974df8b3bac41d26555080b02e249/OpenContent/Components/DnnEntitiesAPIController.cs#L660

**Comment by sachatrauwaen** [comment]
fixed and will be released in next version
