### ISSUE TITLE
When on the same tab as a Ventrian News module, clicking to read more of a specific article opens both modules

### ISSUE THREAD

**Issue by RichardHowells** [sachatrauwaen/OpenContent#185]
I hoped to migrate from VN to OpenContent by placing both on a page and indicating that the VN material was 'archive'.

I find that a click to 'read more' in either module may open the detail content view for both modules.

It appears that this happens because in (say) this url... 

https://staging-broad-town.dynamisys.co.uk/Community-Information/Broad-Town-News/ID/7/Broad-Town-NewsMay-2015

the section ...ID/7... is processed by both modules.  If there is an article with ID 7 in both, then both will open.

I don't know if this would be normal behaviour for any DNN site, but it is not what I expected.

**Comment by Timo-Breumelhof** [comment]
That's how DNN works. 
DNN handles the page URL, the modules handle the rest of the URL.

[www.mywebsite/articles/id/123](https://staging-broad-town.dynamisys.co.uk/Community-Information/Broad-Town-News)

In a way, the rest of the URL instructs a module what to show on a page.
If two modules on the same page use the same (query string) parameter for that, they will both respond to it.
And both modules use "id" to determine what detail article to show.

I think I would place NA on a separate page en use "NA Latest" to show your archived list.

**Comment by RichardHowells** [comment]
@Timo-Breumelhof  thank you for confirming my guesses

**Comment by Timo-Breumelhof** [comment]
:-)
