### ISSUE TITLE
Conversion to VUE templates

### ISSUE THREAD

**Issue by schotman** [sachatrauwaen/OpenContent#186]
This issue describes the conversion for new VUE templates. It will be updated when relevant.

The following field types are not available in the VUE version:

- select2 (replace with relation)
- wysihtml (replace with ckeditor)

You need to change the option file for this.

The builder.json file is needed for the availability of the form builder. The content is no longer used.

**Comment by Timo-Breumelhof** [comment]
see: https://opencontent.readme.io/v5.0/docs/migrating-existing-templates-to-builder-v2
