### ISSUE TITLE
Unable to save after change sort order

### ISSUE THREAD

**Issue by wbonekamp** [sachatrauwaen/OpenContent#187]
When you have multiple items and you change the sort order you can't save the changes anymore.
The checkbox field of these items are set to empty as soon as you change the sort order. We think that's the cause of this issue.

We used OC 4.7 in DNN 9.6x - 9.10.1

**Comment by Timo-Breumelhof** [comment]
What kind of template? Multiple with drag and drop ordering?

**Comment by wbonekamp** [comment]
Carousel, panel template:

![image](https://user-images.githubusercontent.com/7567981/150362128-f4124535-14b7-4da5-9d40-710e2145e908.png)

**Comment by Timo-Breumelhof** [comment]
If you first add an item and then try to change the order there's a bug which is a known issue.
Actually it's an issue in Alpaca.

**Comment by Timo-Breumelhof** [comment]
Sacha is working on replacing Alpaca with Vue.Js, which should fix this.

**Comment by wbonekamp** [comment]
So the issue is in the dnn.js of Alpaca (theme)?

**Comment by Timo-Breumelhof** [comment]
No, it's a bug in Alpaca.js (use to render the edit screen) AFAIK

**Comment by wbonekamp** [comment]
@sachatrauwaen When do you think the replacement to Alpaca Vue.js is ready for release? Will it be available in 4.8 or 4.7.1?

You would really help us out!!!

thanks Timo for your reaction/support!

**Comment by Timo-Breumelhof** [comment]
v5 is in testing phase ATM, no planned release date yet and it will not be 100% downwards compatible (just as a warning)

**Comment by wbonekamp** [comment]
If you need an extra tester... let me know... 👍 

good to hear it's almost there....

**Comment by Timo-Breumelhof** [comment]
@wbonekamp did you manage to do some testing of OC 5?

**Comment by wbonekamp** [comment]
Did fix the issue! Vue works great!
