### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by MaiklT** [sachatrauwaen/OpenContent#199]
When clicking "Download" in the menu on the left side of [Getting Started with Open Content](https://opencontent.readme.io/docs) it leads to [an old page on CodePlex](https://opencontent.codeplex.com/releases).

Same thing in [View.resx](https://github.com/sachatrauwaen/OpenContent/blob/e9de4aecf5e974df8b3bac41d26555080b02e249/OpenContent/App_LocalResources/View.ascx.resx#L192) - and the link there starts with "[http://https://](#)".

**Comment by Timo-Breumelhof** [comment]
@MaiklT thank you for reporting this!
I fixed the documentation pages.
And https://github.com/sachatrauwaen/OpenContent/pull/200

**Comment by Timo-Breumelhof** [comment]
I guess this will be part of version 05.00.03
