### ISSUE TITLE
Cannot upload image - ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by RichardHowells** [sachatrauwaen/OpenContent#201]
On my server I find that I cannot upload images.  When Image uploads fail browser tools shows an error ERR_HTTP2_PROTOCOL_ERROR.  Plain content updates work correctly.

Even stranger; running the same website locally on my laptop the image upload works.  I have almost the same IIS on my laptop (10.0.22000.708) as on the server (10.0.14393.0)

Problem shows up in chrome and in edge (only tried the two browsers)

If I run the site from a browser running locally on the actual server I get the same issue.

So it feels to me like something external to IIS, or maybe in IIS configuration, but I am now out of ideas.

The site is configured to use the CKEditor. Same site has no trouble using CKEditor to upload images for (say) the HTMLModule.  I *think* that OpenContent comes with its own instance of CKEditor - so this might not be significant.

Any ideas for the root cause of this?  Even better any ideas to correct it?

**Comment by RichardHowells** [comment]
I do mean from the Open Content CKEditor.  So clicking the image icon, and selecting a file.  The file does preview in the template window and also shows a javascript alert saying "Your image could not be uploaded due toa network error"

**Comment by Timo-Breumelhof** [comment]
Hmm, I'm confused. I thought the file browser normally does not work at all in the OC Ckeditor..

**Comment by RichardHowells** [comment]
A little more background - I am creating an image gallery.  So I'm using the Bootstrap3Accordion template.  My plan is to have each image along with any caption/supporting text in an single accordion panel.  I'd be happy to hear if there is a better approach.

I assumed that, just like the traditional HTML module I would use the CKEditor to both edit the text and to upload and include the image.  It's at the upload image stage that it fails (as described above) on my server.  It works on my laptop.  Again I'd be happy to hear if there is a better approach.

Although it's a (very!) mature DNN install (on v9.4.4), adding OpenContent is very recent.  It's my first experience with the OC module.

**Comment by Timo-Breumelhof** [comment]
Hi Richard,

Ok that's not the most optimal way to use Open Content IMO.
As it's intended as a structured content module, it's mostly better to separate the data into separate fields as much as possible. So use [textarea] or [ckeditor] for the text and [imagex] for the image.
It also makes editing more "Structured" and leads to less issues during rendering.
BTW, what version of OC are you using?
(note to self, should really finish that OC intro video..)

**Comment by RichardHowells** [comment]
Thank you.  I'd love to try those things, but they are meaningless to me.

I'm saddened to say that I find the module obviously powerful and completely unapproachable.

I'm a developer - I feel that I /should/ be able to find my way through this, but I can't

**Comment by Timo-Breumelhof** [comment]
Ok I'm interested as to why that is. Would you be prepared to do a meeting somewhere next week?

**Comment by RichardHowells** [comment]
YES!!!  Definitely!  Yes please.

I'm working in India ATM so I'm on UTC+5.5.  I generally get back to my hotel around 7:30pm IST (2pm UTC).  Anytime up to about 10pm IST.  Next week I have constraints.  I prefer Monday/Tuesday.  I can host a long duration Zoom meeting.  Please ping me an initial contact email to richard at dynamisys dot co dot uk.

Thanks

**Comment by RichardHowells** [comment]
I'm still puzzled about the original error though.  It works on my laptop.  What's different about putting on a server?

**Comment by Timo-Breumelhof** [comment]
I have no answer to your issue TBH, that's weird.
Did you try resetting the NTFS rights on the file system?

**Comment by Timo-Breumelhof** [comment]
Email sent

**Comment by RichardHowells** [comment]
Original issue is RESOLVED.  I applied all the available Windows Updates to my server and the problem has gone away.  I don't know which update(s) solved the problem.
