### ISSUE TITLE
Builder v2 styling

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#209]
I have a list of roles in the edit screen and would like to make them multi-column using CSS column-count.
But there is no real way to address the fields currently see:

![image](https://user-images.githubusercontent.com/8999382/223478617-1f72b47e-93f9-4b07-b7fa-39f4caf62f11.png)

For styling purposes it would be nice if one could address the fields using CSS.

One solution for this could be to add a class for field type and field name:

![image](https://user-images.githubusercontent.com/8999382/223480024-21b3c066-24b9-4317-a03b-4a877be4b784.png)

**Comment by sachatrauwaen** [comment]
Is it not easyer to add form-check-inline for checkboxlist ?

see https://getbootstrap.com/docs/4.0/components/forms/#inline

**Comment by Timo-Breumelhof** [comment]
Yes that's a good option. But what I like about the suggested classes is that I can manipulate the form the way I want, not only for this one. 
Or maybe we just add options for those use cases too?
I can think of a width setting for instance (BS columns)
