### ISSUE TITLE
Cropped images too large in 5.0.6

### ISSUE THREAD

**Issue by b-creative** [sachatrauwaen/OpenContent#221]
When using the imagebrowser field, in OC 5.0.6, and I upload a 2.8 MB jpg, and I have set a crop of 724x1020, the cropped file is 1.37 MB. Why? And can I adjust this? I would rather expect something like 140K.

**Comment by Timo-Breumelhof** [comment]
I guess it's the jpeg quality? Not sure if you can change that TBH.. @sachatrauwaen ?

**Comment by b-creative** [comment]
I believe this is fixed in version 5.0.9
