### ISSUE TITLE
Don't show edit buton after placing "Satrabel.DnnUsers" template

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#223]
After placing the OC module and selecting a template using the Satrabel.DnnUsers DataSource  the Admin gets to see an 'Edit" button.
When you click that button the page seems to freeze.
IMO there's no need for this button to show up at all, is it possible to not show i when this DataSource is used?

**Comment by sachatrauwaen** [comment]
fixed in v 5.0.10
