### ISSUE TITLE
Add support for edit.css

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#228]
As we have support for edit.js, it would be nice to be able to also add edit.css as an option.
This will allow us to visually manipulate the edit screen to make it clearer.

My use case is to add a separator-line between fields, with support for edit.css that can easily be done.
One could in theory add the styling to the Theme too, but that does not scale very well IMO..

**Comment by sachatrauwaen** [comment]
Available in version 5.1
