### ISSUE TITLE
CKEditor shows upgrade warning

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#243]
The CKEditor shows a security warning (classic builder)

<img width="703" alt="Scherm_afbeelding_2024-07-16_om_10 38 39" src="https://github.com/user-attachments/assets/34c22857-d3d5-49ef-aa14-a72a10d4b00f">

**Comment by Timo-Breumelhof** [comment]
@sachatrauwaen I checked the code and I think it's an issue with the used CKEditor  version in https://github.com/sachatrauwaen/lamavue/blob/master/package.json?

**Comment by sachatrauwaen** [comment]
Fixed in 05.01.03
