### ISSUE TITLE
BootstrapIconsColumnEffect Heading Issues

### ISSUE THREAD

**Issue by TopCat6** [sachatrauwaen/OpenContent#26]
When narrowing the window, the Heading is not centered, if the standard bootstrap heading size is not used. Changing line 3 of icon-hover.css to the following, fixes this issue:
From:  `.icon_hover .fa-effect{position:absolute;top:0;left:40%;}`
To:  `.icon_hover .fa-effect{margin-top:-50px;}`

Also, could you please add `h4` to the styles for `h3` on lines 57 and 58 of the same css file, so that it becomes easy to change the template to apply to h4 instead of h3, on sites where it is preferable.

Thank you.

**Comment by sachatrauwaen** [comment]
I update the template and i rename the css file to template.css.
So now you can edit the css file from Edit Template Files
