### ISSUE TITLE
Edit Option for Previous Version broken

### ISSUE THREAD

**Issue by TopCat6** [sachatrauwaen/OpenContent#27]
When using "Edit Content" for any template, an option is provided to roll back to a previous version. However, all the Date/Time items are identical and choosing any one other than "( current )" causes an error dialog box that says: "Uh-oh, something broke: Internal Server Error"

![image](https://user-images.githubusercontent.com/17517455/30405025-74ae351e-989e-11e7-9366-540ddad25f40.png)
![image](https://user-images.githubusercontent.com/17517455/30405067-a75407be-989e-11e7-828c-1cf68e4ffc9b.png)

The Admin Logs do not show any error message.

**Comment by sachatrauwaen** [comment]
Thanks for reporting the issue.

The bug is fixed in version 3.4.2 released today
