### ISSUE TITLE
Readme.io links not working

### ISSUE THREAD

**Issue by robert-m** [sachatrauwaen/OpenContent#29]
Hi Sacha! Firstly thank-you so much for the **amazing** module. You are a life saver :-)

The readme.io release links aren't working. Clicking on the links throws a permission error

**Exampe :** https://dash.readme.io/project/opencontent/v3.4/blog/opencontent-35

<img width="325" alt="screenshot 2017-12-05 19 58 57" src="https://user-images.githubusercontent.com/2234549/33598434-d7b66534-d9f6-11e7-932f-67bc0a0fd709.png">

**Comment by mvanlaar** [comment]
Here is the correct link:
https://opencontent.readme.io/blog/opencontent-35

**Comment by sachatrauwaen** [comment]
Thanks for the info
