### ISSUE TITLE
File2 crashes when folder does not exist

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#34]
OC 03.05.02

Options:

"File": {
    "type": "file2",
    "filter":"^.*\.(jpg|JPG|gif|GIF|doc|DOC|pdf|PDF)$",
    "folder":"Files/MyFolder",
    "showFileUpload":true,
    "showUrlUpload":true  
}

When "MyFolder" does not exist I get a JS error:

{"message":"Unable to load data from uri : undefined","stage":"DATASOURCE_LOADING_ERROR","details":{"jqXHR":{"readyState":4,"responseText":"{\"Message\":\"An error has occurred.\",\"ExceptionMessage\":\"Value cannot be null.\\r\\nParameter name: folder\",\"ExceptionType\":\"System.ArgumentNullException\",\"StackTrace\":\"   at DotNetNuke.Services.FileSystem.FolderManager.GetFiles(IFolderInfo folder, Boolean recursive, Boolean retrieveUnpublishedFiles)\\r\\n   at Satrabel.OpenContent.Components.DnnEntitiesAPIController.FilesLookup(String q, String d, String filter)\"}","status":500,"statusText":"Internal Server Error"},"textStatus":"error","errorThrown":"Internal Server Error"}}

When I manually create the folder and sync the DNN file system the error is gone

**Comment by robsiera** [comment]
not sure if we really want to facilitate automatic creation of folders. But at least [I made sure](https://github.com/sachatrauwaen/OpenContent/commit/d9f9647b1bde9320b0ba838086c3437e73a6d59a) that a more meaningful error is being thrown.

**Comment by Timo-Breumelhof** [comment]
Ok, thanks. 
Why would you create a folder for images but not for files?
