### ISSUE TITLE
Accordian headings not in search results

### ISSUE THREAD

**Issue by TopCat6** [sachatrauwaen/OpenContent#36]
Any idea why site search results do not include the text located in the headings of the Accordian template? Is there an easy fix? 
Just to be clear, the heading of the OpenContent/Accordian **module** appears in the search results, but not the text of the headings of each Accordian item. (I only have images in the content, so I don't know about that being indexed.)

**Comment by sachatrauwaen** [comment]
Do you look already tothis documentation : 

https://opencontent.readme.io/docs/dnn-search-integration

**Comment by TopCat6** [comment]
It seems that the Accordion template does not use multi-item data structure, and therefore cannot be searched. It would have to be converted into a multi-item template before search would work. So, despite the two erroneous trailing commas in the above code, the template would have to be re-written to be multi-item before search would work. Am I correct in that assessment?

**Comment by sachatrauwaen** [comment]
Hi, it have to work with a non multi item template.

Here a exemple manifest for a signle item template.

{
    "templates": {
        "template": {
            "type": "single",
            "title": "template",           
            "main": {
                "template": "template.hbs",
              	"dnnsearch": true,
                 "dnnSearchTitle": "{{#each Boxes}}{{Title}} {{/each}}",
                 "dnnSearchDescription": "{{#each Boxes}}{{Description}} {{/each}}",
                 "dnnSearchText": "{{#each Boxes}}{{Title}} {{Description}} {{/each}}"
            }
        }
    }
}

After changing the manifest to switch template and reselect template and save.

**Comment by TopCat6** [comment]
Thank you for this clarification. I tried your manifest file, and also a version without the #each containers. I also went to 'switch template', reselected it and saved. I also tried saving the template again. Still no luck with Search. I am now pursuing a work-around solution.
Thanks for your help, anyway.
