### ISSUE TITLE
Accordion postback fails on firefox and safari

### ISSUE THREAD

**Issue by aldeng11** [sachatrauwaen/OpenContent#39]
I see this in the console:

 [Show/hide message details.] TypeError: access to strict mode caller function is censored ScriptResource.axd:5:13769
_doPostBack
https://imcw.azurewebsites.net/ScriptResource.axd:5:13769
Function.createDelegate/<
https://imcw.azurewebsites.net/ScriptResource.axd:5:305
alpacaEngine.engine/self.FormSubmit/<
https://imcw.azurewebsites.net/DesktopModules/OpenContent/js/alpacaengine.js:276:21
fire
https://imcw.azurewebsites.net/Resources/libraries/jQuery/03_02_01/jquery.js:3317:11
fireWith
https://imcw.azurewebsites.net/Resources/libraries/jQuery/03_02_01/jquery.js:3447:7
done
https://imcw.azurewebsites.net/Resources/libraries/jQuery/03_02_01/jquery.js:9272:5
callback/<
https://imcw.azurewebsites.net/Resources/libraries/jQuery/03_02_01/jquery.js:9514:9

**Comment by sachatrauwaen** [comment]
not really a open content issue

**Comment by aldeng11** [comment]
You’re saying this is alpaca?  It still makes editing OC forms on Firefox and safari impossible. Has this been addressed in a new alpaca release?

**Comment by sachatrauwaen** [comment]
Hi, maybe i missread the issue.

You talking about accordeon in the editor of opencontent.

Can you tell me if you can reproduce it in oc 4.1 and in wich standard oc template ?

**Comment by aldeng11** [comment]
I am talking about the Edit Content function for any structured content.  It does not fully support Firefox or Safari.  I checked and the error is the same in v4.1.  Clicking the Save button does not close the pop-up and refresh the page due to the javascript error that is preventing postback.  The error in console is TypeError: access to strict mode caller function is censored.

If you manually close the popup and refresh the page, you see that the content did save.  However, my admins don't know to do this, so I have had to tell them we don't support Firefox or Safari.

Alden Gannon
Six Fish, LLC
206.201.2566
On 5/12/2019 3:27:39 AM, Sacha <notifications@github.com> wrote:
Hi, maybe i missread the issue.
You talking about accordeon in the editor of opencontent.
Can you tell me if you can reproduce it in oc 4.1 and in wich standard oc template ?

**Comment by sachatrauwaen** [comment]
Fixed in v 1.4.2
Can you confirm ?

**Comment by aldeng11** [comment]
Do you mean v4.2?

Alden Gannon
Six Fish, LLC
206.201.2566
On 5/29/2019 6:58:11 AM, Sacha <notifications@github.com> wrote:
Fixed in v 1.4.2
Can you confirm ?

**Comment by aldeng11** [comment]
After upgrade, I get this error:

Error: Neighborhood sitting groups c is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: d:\home\site\wwwroot\DesktopModules\OpenContent\View.ascx(53): error CS0103: The name 'Resource' does not exist in the current context ---> System.Web.HttpCompileException: d:\home\site\wwwroot\DesktopModules\OpenContent\View.ascx(53): error CS0103: The name 'Resource' does not exist in the current context at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc) at DotNetNuke.UI.Modules.WebFormsModuleControlFactory.CreateModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration) at DotNetNuke.UI.Modules.ModuleControlFactory.LoadModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration) at DotNetNuke.UI.Modules.ModuleHost.LoadModuleControl() --- End of inner exception stack trace ---

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/2/2019 10:08:07 PM, Alden Gannon <alden@six.fish> wrote:
Do you mean v4.2?

Alden Gannon
Six Fish, LLC
206.201.2566
On 5/29/2019 6:58:11 AM, Sacha <notifications@github.com> wrote:
Fixed in v 1.4.2
Can you confirm ?

**Comment by sachatrauwaen** [comment]
Hi,

Yes it's in v4.2 that i mean.

The last errors you  manion, sound more like the module is not correctelly installed.

Can you try to reinstall the module.

**Comment by aldeng11** [comment]
Yes, I tried that. No good. Is there a way to downgrade without losing my data? Can I uninstall?

AldenG
206.201.2566
Excuse the brevity.  Typed on my iPhone with fat clumsy thumbs.

**Comment by sachatrauwaen** [comment]
I sujest you  to start with re install opencontent v4.2 without uninstall

**Comment by aldeng11** [comment]
I did that, no difference.

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:13:52 AM, Sacha <notifications@github.com> wrote:
I sujest you to start with re install opencontent v4.2 without uninstall

**Comment by aldeng11** [comment]
Can I give you host access for troubleshooting?

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:14:55 AM, Alden Gannon <alden@six.fish> wrote:
I did that, no difference.

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:13:52 AM, Sacha <notifications@github.com> wrote:
I sujest you to start with re install opencontent v4.2 without uninstall

**Comment by sachatrauwaen** [comment]
You always have this error : DotNetNuke.Services.Exceptions.ModuleLoadException: d:\home\site\wwwroot\DesktopModules\OpenContent\View.ascx(53): error CS0103: The name 'Resource' does not exist in the current context ?


if yes can you compare the opencontent.dll in  your bin folder and the same dll in the  bin folder of the opencon,tent install zip . Is it the same ?

**Comment by aldeng11** [comment]
The dlls did not copy.  I copied the 3 dlls and get this: https://seattleinsight.org/ [https://seattleinsight.org/]

Nothing in the log file.

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:26:18 AM, Sacha <notifications@github.com> wrote:
You always have this error : DotNetNuke.Services.Exceptions.ModuleLoadException: d:\home\site\wwwroot\DesktopModules\OpenContent\View.ascx(53): error CS0103: The name 'Resource' does not exist in the current context ?
if yes can you compare the opencontent.dll in your bin folder and the same dll in the bin folder of the opencon,tent install zip . Is it the same ?

**Comment by aldeng11** [comment]
Turned on remote errors and have:

[FileLoadException: Could not load file or assembly 'Handlebars' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] [FileLoadException: Could not load file or assembly 'Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0 System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +478 System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +128 System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +22 System.Reflection.Assembly.Load(String assemblyString) +34 System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +48 [ConfigurationErrorsException: Could not load file or assembly 'Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +767 System.Web.Configuration.CompilationSection.LoadAllAssembliesFromAppDomainBinDirectory() +256 System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai) +58 System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig) +281 System.Web.Compilation.BuildManager.GetPreStartInitMethodsFromReferencedAssemblies() +70 System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +137 System.Web.Compilation.BuildManager.ExecutePreAppStart() +172 System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +848 [HttpException (0x80004005): Could not load file or assembly 'Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532 System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +113 System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +714

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:38:35 AM, Alden Gannon <alden@six.fish> wrote:
The dlls did not copy.  I copied the 3 dlls and get this: https://seattleinsight.org/ [https://seattleinsight.org/]

Nothing in the log file.

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:26:18 AM, Sacha <notifications@github.com> wrote:
You always have this error : DotNetNuke.Services.Exceptions.ModuleLoadException: d:\home\site\wwwroot\DesktopModules\OpenContent\View.ascx(53): error CS0103: The name 'Resource' does not exist in the current context ?
if yes can you compare the opencontent.dll in your bin folder and the same dll in the bin folder of the opencon,tent install zip . Is it the same ?

**Comment by aldeng11** [comment]
This is the handlebars in my web.config:

      
      
      <dependentAssembly>
        <assemblyIdentity name="Handlebars" publicKeyToken="22225d0bf33cd661" />
        <bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="1.0.0.0" />
      </dependentAssembly>

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:41:59 AM, Alden Gannon <alden@six.fish> wrote:
Turned on remote errors and have:

[FileLoadException: Could not load file or assembly 'Handlebars' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] [FileLoadException: Could not load file or assembly 'Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0 System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +478 System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +128 System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +22 System.Reflection.Assembly.Load(String assemblyString) +34 System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +48 [ConfigurationErrorsException: Could not load file or assembly 'Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +767 System.Web.Configuration.CompilationSection.LoadAllAssembliesFromAppDomainBinDirectory() +256 System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai) +58 System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig) +281 System.Web.Compilation.BuildManager.GetPreStartInitMethodsFromReferencedAssemblies() +70 System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +137 System.Web.Compilation.BuildManager.ExecutePreAppStart() +172 System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +848 [HttpException (0x80004005): Could not load file or assembly 'Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532 System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +113 System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +714

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:38:35 AM, Alden Gannon <alden@six.fish> wrote:
The dlls did not copy.  I copied the 3 dlls and get this: https://seattleinsight.org/ [https://seattleinsight.org/]

Nothing in the log file.

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:26:18 AM, Sacha <notifications@github.com> wrote:
You always have this error : DotNetNuke.Services.Exceptions.ModuleLoadException: d:\home\site\wwwroot\DesktopModules\OpenContent\View.ascx(53): error CS0103: The name 'Resource' does not exist in the current context ?
if yes can you compare the opencontent.dll in your bin folder and the same dll in the bin folder of the opencon,tent install zip . Is it the same ?

**Comment by aldeng11** [comment]
Temporarily replaced DLLs to get my site back up.

https://seattleinsight.org/ [https://seattleinsight.org/]



Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:52:03 AM, Alden Gannon <alden@six.fish> wrote:
This is the handlebars in my web.config:

      
      
      <dependentAssembly>
        <assemblyIdentity name="Handlebars" publicKeyToken="22225d0bf33cd661" />
        <bindingRedirect oldVersion="0.0.0.0-32767.32767.32767.32767" newVersion="1.0.0.0" />
      </dependentAssembly>

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:41:59 AM, Alden Gannon <alden@six.fish> wrote:
Turned on remote errors and have:

[FileLoadException: Could not load file or assembly 'Handlebars' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] [FileLoadException: Could not load file or assembly 'Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0 System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +478 System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +128 System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +22 System.Reflection.Assembly.Load(String assemblyString) +34 System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +48 [ConfigurationErrorsException: Could not load file or assembly 'Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +767 System.Web.Configuration.CompilationSection.LoadAllAssembliesFromAppDomainBinDirectory() +256 System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai) +58 System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig) +281 System.Web.Compilation.BuildManager.GetPreStartInitMethodsFromReferencedAssemblies() +70 System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +137 System.Web.Compilation.BuildManager.ExecutePreAppStart() +172 System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +848 [HttpException (0x80004005): Could not load file or assembly 'Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)] System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532 System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +113 System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +714

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:38:35 AM, Alden Gannon <alden@six.fish> wrote:
The dlls did not copy.  I copied the 3 dlls and get this: https://seattleinsight.org/ [https://seattleinsight.org/]

Nothing in the log file.

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 9:26:18 AM, Sacha <notifications@github.com> wrote:
You always have this error : DotNetNuke.Services.Exceptions.ModuleLoadException: d:\home\site\wwwroot\DesktopModules\OpenContent\View.ascx(53): error CS0103: The name 'Resource' does not exist in the current context ?
if yes can you compare the opencontent.dll in your bin folder and the same dll in the bin folder of the opencon,tent install zip . Is it the same ?

**Comment by sachatrauwaen** [comment]
So this mean opencontent is not instaled right.

You have to check the file permissions of the dnn installation.
the website user need to have modify permissions on all folders and files.

aftr that reinstall opencontent 4.2

**Comment by aldeng11** [comment]
I install modules on that site all the time. Three others yesterday worked fine. 

AldenG
206.201.2566
Excuse the brevity.  Typed on my iPhone with fat clumsy thumbs.

**Comment by aldeng11** [comment]
Tried again, same result.  This is an Azure App Service, and there are no file permissions to set.

At this point, if I roll back my database, I will lose 2 days of edits.  Can you simply tell me what to ftp where?  Can I give you ftp access and you fix it?

This is a production environment and all the Open Content pages are down.

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 12:50:17 PM, Alden Gannon <alden@six.fish> wrote:
I install modules on that site all the time. Three others yesterday worked fine. 


AldenG
206.201.2566

Excuse the brevity.  Typed on my iPhone with fat clumsy thumbs.

On Jun 3, 2019, at 9:26 AM, Sacha <notifications@github.com [mailto:notifications@github.com]> wrote:


You always have this error : DotNetNuke.Services.Exceptions.ModuleLoadException: d:\home\site\wwwroot\DesktopModules\OpenContent\View.ascx(53): error CS0103: The name 'Resource' does not exist in the current context ?
if yes can you compare the opencontent.dll in your bin folder and the same dll in the bin folder of the opencon,tent install zip . Is it the same ?

**Comment by aldeng11** [comment]
Everything in the DesktopModules/OpenContent directory seems to have copied.  It seems I'm only missing are the right DLLs.  Can you send them to me?  I will ftp them to the bin directory.

I'm guessing you have a wrong DLL in the package.

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 6:52:36 PM, Alden Gannon <alden@six.fish> wrote:
Tried again, same result.  This is an Azure App Service, and there are no file permissions to set.

At this point, if I roll back my database, I will lose 2 days of edits.  Can you simply tell me what to ftp where?  Can I give you ftp access and you fix it?

This is a production environment and all the Open Content pages are down.

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 12:50:17 PM, Alden Gannon <alden@six.fish> wrote:
I install modules on that site all the time. Three others yesterday worked fine. 


AldenG
206.201.2566

Excuse the brevity.  Typed on my iPhone with fat clumsy thumbs.

On Jun 3, 2019, at 9:26 AM, Sacha <notifications@github.com [mailto:notifications@github.com]> wrote:


You always have this error : DotNetNuke.Services.Exceptions.ModuleLoadException: d:\home\site\wwwroot\DesktopModules\OpenContent\View.ascx(53): error CS0103: The name 'Resource' does not exist in the current context ?
if yes can you compare the opencontent.dll in your bin folder and the same dll in the bin folder of the opencon,tent install zip . Is it the same ?

**Comment by sachatrauwaen** [comment]
you can try to copy all dlls of the bin folder  in the zip install package.

**Comment by sachatrauwaen** [comment]
whats your dnn version ? and dot.net version ?

**Comment by aldeng11** [comment]
9.2 dnn, 4.7 .net

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 10:25:17 PM, Sacha <notifications@github.com> wrote:
whats your dnn version ? and dot.net version ?

**Comment by aldeng11** [comment]
I did this, it results in the error:

[FileLoadException: Could not load file or assembly 'Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]

What version of handlebars should be in my web.config? Is it not updating this line correctly?

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 10:24:44 PM, Sacha <notifications@github.com> wrote:
you can try to copy all dlls of the bin folder in the zip install package.

**Comment by aldeng11** [comment]
Fixed.  I needed to update that version of the handlebars.dll binding redirect in my web.config to 1.10.1.0

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 10:30:16 PM, Alden Gannon <alden@six.fish> wrote:
I did this, it results in the error:

[FileLoadException: Could not load file or assembly 'Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]

What version of handlebars should be in my web.config? Is it not updating this line correctly?

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 10:24:44 PM, Sacha <notifications@github.com> wrote:
you can try to copy all dlls of the bin folder in the zip install package.

**Comment by aldeng11** [comment]
Still no firefox or safari support. JS save blocked with same error as before:

TypeError: access to strict mode caller function is censored.

I have been able to get around this in the past by setting a timer which will trigger in a safe context, then running your JS.

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 10:49:35 PM, Alden Gannon <alden@six.fish> wrote:
Fixed.  I needed to update that version of the handlebars.dll binding redirect in my web.config to 1.10.1.0

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 10:30:16 PM, Alden Gannon <alden@six.fish> wrote:
I did this, it results in the error:

[FileLoadException: Could not load file or assembly 'Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]

What version of handlebars should be in my web.config? Is it not updating this line correctly?

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/3/2019 10:24:44 PM, Sacha <notifications@github.com> wrote:
you can try to copy all dlls of the bin folder in the zip install package.

**Comment by aldeng11** [comment]
This issue is now fixed.

**Comment by sachatrauwaen** [comment]
Nice you fixid. What was the issue ?
