### ISSUE TITLE
Handlebars {{#ifor}} error

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#43]
used:
<div class="{{#ifor Image YouTubeId}}col-md-6{{else}}col-md-12{{/ifor}}">

Error:
Could not find helper '#ifor'

DNN8, OC 3.5.4

**Comment by Timo-Breumelhof** [comment]
sorry html got lost:
&lt;div class=&quot;{{#ifor Image YouTubeId}}col-md-6{{else}}col-md-12{{/ifor}}&quot;&gt;

**Comment by sachatrauwaen** [comment]
fixed
