### ISSUE TITLE
DNN 9.2.2 save issue

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#44]
I used OC 3.5.4 on DNN 9.2.2 (on two installations) and if I click the save button, nothing happens.
As soon as I disable pop-ups:

UPDATE [PortalSettings]

SET SettingValue = 'False'

WHERE SettingName = 'EnablePopUps'

And Restart DNN, I can save.
Not really an issue as I always disable the pop-ups, but it might be an issue for others.
(using s single item template, not sure if that has anything to do with it)

**Comment by Timo-Breumelhof** [comment]
BTW, this was a fresh install of DNN 9.2.2 and OC.

**Comment by OllyHodgson** [comment]
In Firefox - I wonder if this is this related to #39? Were there any errors in the browser console, @Timo-Breumelhof?

**Comment by Timo-Breumelhof** [comment]
> 
> 
> In Firefox - I wonder if this is this related to #39? Were there any errors in the browser console, @Timo-Breumelhof?

I did not do any further testing yet as I was on a deadline, but it could be..

**Comment by sachatrauwaen** [comment]
fixes in v4.1
