### ISSUE TITLE
Feature request: PersonaBar extension for "Global Settings"

### ISSUE THREAD

**Issue by OllyHodgson** [sachatrauwaen/OpenContent#45]
It would be really useful for OpenContent to include a PersonaBar extension, which gives me access to the Global Settings, along with some others, for example "Reindex all modules".
 
I don't have Super User rights on our production websites (only dev and test installations). For production configuration changes, I have to write instructions for our IT Operations dept to follow. It would be much easier if I didn't have to describe the steps needed to edit the page, find the global settings menu item, etc.

**Comment by sachatrauwaen** [comment]
I understand, but it is only available in dnn 9
so it need to maintain 2 oc versions.

**Comment by Timo-Breumelhof** [comment]
Agreed
