### ISSUE TITLE
No Results Found

### ISSUE THREAD

**Issue by hismightiness** [sachatrauwaen/OpenContent#46]
I haven't done much.  I'm just trying to duplicate the "catalog" demo using the Catalog template.  So far, I'm having very little luck.

I've created a new template based on the Catalog template and updated the fields and options to match what I need.  I changed one field name and added another.  I also added some categories.

I then added a new content item and saved it.  Nothing shows.  I get "No Results Found" and the word "Processing" is also shown beneath it.  

If I search for the single content item using a word in its title or select an associated category, nothing happens.  I don't even see any errors in the console.  

I can edit the raw data and see the single content item I've saved, but I have no clue how to show the content item, nor do I know how to edit it in the front end.

Is this an expected on-boarding experience?  What might I be doing wrong?

**Comment by hismightiness** [comment]
Where's the template that can do this out-of-the-box?

http://www.openextensions.net/dnn-modules/opencontent/catalog#paging:number=5|paging:currentPage=0

**Comment by sachatrauwaen** [comment]
Hi, what you you see on the demo page, is the same as the catalog template you can select in the web templates within opencontent.

Do you have javascript errors ?
If you anlyse the source html of the page, can you find the content ?

To dump the all the data you can try  {{convertToJson this}} at the begining of the template.

**Comment by hismightiness** [comment]
Okay, I swear the out-of-the-box template wasn't working before, but I just tried it on a clean instance and it is indeed working, so I must have broken it at some point when adding the additional fields I need. The JSON does return the required items.

When trying to figure out how to use this module, I found that the categories.hbs template was rendering everything on the default view, when I expected for the template.hbs file to be doing that.  

I'm still a novice to things when it comes to handlebars and how they work in your module, so please excuse any "dumb" questions...

In the categories.hbs file, there doesn't appear to be any code to render results... Should I just copy the code from the template.hbs file, or is it more complicated than that?

**Comment by sachatrauwaen** [comment]
Hi, the catalog template (folder) comes with 2 templtes : 1) list 2) categories.

And have just seen that de 2) categories template is buggy (i have to remove them from this exemple template)

So best is to go to Menu Switch template and chose template "Calalog - list". This one work good for the catalog .

This template is composed of 2 files : template.hbs and item.hbs (included with {{> item}} ).

This template use jplist (js plugin) to implement filtering and paging.

**Comment by hismightiness** [comment]
Can you contact me at will@upendoventures.com with your rate?   I really need help getting this figured out.

**Comment by Timo-Breumelhof** [comment]
Will, a hint: as jplist is doing the filtering on html attributes, when you change the names of fields, this will most likely result in no data showing.
