### ISSUE TITLE
Articles template always shows "No results found"

### ISSUE THREAD

**Issue by hismightiness** [sachatrauwaen/OpenContent#47]
In a clean instance of DNN 9.1.1. and OpenContent 3.6.0, the "No results found" message is always displayed, even if there are results shown.  From what I can tell, the jplist plugin is supposed to toggle this message, but it isn't.  

I've added custom jQuery code to toggle this as a workaround, but it only confuses the jplist plugin - sometimes toggling the display of this text twice.  If someone has another workaround, please let me know.

Steps to Reproduce:

1. Clean instance of DNN 9.1.1 and OpenContent 3.6.0.
2. Add a page and place the OpenContent module on it.
3. Configure the module to have a few custom categories (using the UI).
4. Add a new content item that has one of the custom categories.
5. Get a fresh load of the page.
6. All items should be shown (only 1 right now).  

Expected Behavior:
The "No results found" message is hidden from view.

Actual Behavior: 
The "No results found" message is displayed.

7. Check a checkbox for a category that the new content item is assigned to.

Expected Behavior:
The "No results found" message is hidden from view.

Actual Behavior: 
The "No results found" message is displayed.

8. Only check a category checkbox that the new content item is NOT assigned to.  All other checkboxes should be unchecked.

Expected & Actual Behavior:
The "No results found" message is displayed.

**Comment by hismightiness** [comment]
No one else has experienced this?  :(

**Comment by Timo-Breumelhof** [comment]
Nope,  Can you send met the template so I can have a look locally?

**Comment by hismightiness** [comment]
@Timo-Breumelhof What way would be best to send it to you?

**Comment by Timo-Breumelhof** [comment]
PM

**Comment by pjones235** [comment]
I did experience this to. Let me look back and see what I did to fix.

**Comment by hismightiness** [comment]
Sorry I haven't gotten the template to you yet, Timo. I'll try to do that soon.  :(

**Comment by hismightiness** [comment]
Sent. (Finally)  :)

**Comment by Timo-Breumelhof** [comment]
Thank. I placed the template on a page and I never get "No results" instead of always.
Did you check the page for HTML errors?

**Comment by hismightiness** [comment]
I don't see any errors in the console.  :(

**Comment by hismightiness** [comment]
I need help with this.  :(

**Comment by hismightiness** [comment]
I'm still not sure how to resolve this.  Normally, I just figure things out.  :D

**Comment by Timo-Breumelhof** [comment]
@hismightiness As I stated before I got a different result with your template. Did you already check the page for HTML errors?

**Comment by hismightiness** [comment]
Yes. I don't see any errors.  I need help with this soon and I'll pay for your time. :)

**Comment by sachatrauwaen** [comment]
Hi,
Just to explain a little but how it works.

In the template there is 

<div class="row jplist-no-results text-shadow align-center">
<p>No results found</p>
</div>

Normally if there is no data, jplist plugin add the class jplist-hidden to the dev with a class jplist-no-results.
This will hide the No results found text.

So you can start by inspecting in the browser tools  if the div with the class jplist-no-results has the jplist-hidden class added. And if this class had display:none.

Otherwise send me a email at sachatrauwaen at yahoo.com with your skypeid and we can have a chat to resolve your issue.
