### ISSUE TITLE
Add Examples to Documentation

### ISSUE THREAD

**Issue by hismightiness** [sachatrauwaen/OpenContent#48]
The documentation does a great job of outlining the technical aspect of an element, like the example below.

https://opencontent.readme.io/v3.5/docs/select2

What it doesn't do is that the example to the next step of showing how to display the saved value in the template files.

Can these be updated to show that?

**Comment by Timo-Breumelhof** [comment]
You mean an example hbs file? Or maybe a downloadable example is even better?

**Comment by hismightiness** [comment]
Just example snippet like the rest of the snippets.  It would go a long way for some new people.  :)

**Comment by Timo-Breumelhof** [comment]
@sachatrauwaen I added an example to the categories Select 2
https://opencontent.readme.io/docs/select2

**Comment by hismightiness** [comment]
Awesome... Thanks!  :)
