### ISSUE TITLE
Typing Interrupted When Using Filter on Catalog List Template

### ISSUE THREAD

**Issue by hismightiness** [sachatrauwaen/OpenContent#50]
As I type, the typing is interrupted as the data is sent back and the items are populated again.  However, when this happens, there are very often keystrokes missed and sometimes the cursor is re-positioned at the beginning of the text in the text box.

This is the textbox in question.  

```html
<input data-path=".title" class="form-control"
        type="text"
        value=""
        placeholder="Filter by Title"
        data-control-type="textbox"
        data-control-name="Title"
        data-control-action="filter" />
```

As far as I can tell, this and the related JS are untouched, so this should be something that anyone can reproduce, once you've added items.  In this case, I have at least 20 items and a few extra fields.  

Any ideas if this is a bug and how to fix it?

**Comment by hismightiness** [comment]
Example Video:  https://www.screencast.com/t/IyCem5ENyvX

**Comment by robsiera** [comment]
add 
    `data-event-name="keydelay"`
like this
```
<input data-path=".title" class="form-control"
        type="text"
        value=""
        placeholder="Filter by Title"
        data-control-type="textbox"
        data-control-name="Title"
        data-control-action="filter" 
        data-event-name="keydelay" />
```
This will improve the experience.

**Comment by hismightiness** [comment]
Thanks for the suggestion.  The good news is that the interruption no longer occurs.  The bad news is that the search never executes now.  If I hit enter to attempt to force it, the page just reloads.

**Comment by sachatrauwaen** [comment]
Here you find more info about how to accomplish it

https://opencontent.readme.io/docs/jplist-tips

(you missing the part to add to template.js)

**Comment by hismightiness** [comment]
@sachatrauwaen I'm a bit of a newbie in this regard.  Can you please be more specific on what I need to resolve?
