### ISSUE TITLE
Switch template does not show skin templates

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#51]
Just logging this, I will check on other installs later to verify.

Add a template to a skin.
Place OC with that template.
rename the folder of the template.
Now try to connect the module to the renamed template.
The skin templates don't show up.

**Comment by pjones235** [comment]
I noticed this as well.

**Comment by sachatrauwaen** [comment]
Do you rename the folder in DNN or on the file system ?
If on the file system, can you try to refresh folders in dnn ?

**Comment by Timo-Breumelhof** [comment]
file system, restart DNN or resync files does not make a difference.

**Comment by Timo-Breumelhof** [comment]
OK, I tested this again and it;s a bit different.
When I rename one folder no skin templates show up.
When I clear DNN cache they do.
