### ISSUE TITLE
Icons field not working any more

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#52]
In open content 3.6, when I choose the icon type the edit screen stays empty.
There's a jquery error in the browser console.

TypeError: type.indexOf is not a function

DNN 7.4.2 OC 3.6 with or without a Bootstrap Skin

I do see jquery on th page wtice, could it be that you are loading jquery in a different way from how the skin does that?

**Comment by Timo-Breumelhof** [comment]
Template:
[IconTest.zip](https://github.com/sachatrauwaen/OpenContent/files/2630115/IconTest.zip)

**Comment by sachatrauwaen** [comment]
Fixed in v 1.4.2
