### ISSUE TITLE
Being able to call resized images in template

### ISSUE THREAD

**Issue by b-creative** [sachatrauwaen/OpenContent#55]
In the past we have worked with a few article modules which all had the possibility to resize the images called in the different templates. Especially helpfull in a list view where many images are shown at once. You can imagine one needs the medium sized image when used in a large image carroussel, a smaller image when calling a list view and a full image when calling the detail view of the article. 

Maybe it possible now already? Or just via a jQuery-plugin? 

Any experiences?

**Comment by Timo-Breumelhof** [comment]
Yes you can do that. The Image cropper field store the corp ratio and does not crop the image itself. In combination with an image Http module you can then have the images created dynamically by changing the url of the image. 
AFAIR, Sacha uses this one which is OS: http://imageprocessor.org/

**Comment by Timo-Breumelhof** [comment]
BTW, please note that from V4 the current cropper fields will be deprecated as all image fields will be merged to one new filed imagex(tended).

**Comment by b-creative** [comment]
...all image fields will be merged into what? Sorry, don't understand...

**Comment by Timo-Breumelhof** [comment]
There are several image related fields in OC, Image, Image2, Cropper, Cropper2.
In OC4, there will be a new field "ImageExtended" which combines all the functionality of those separated fields. The existing ones will keep working but will be marked as deprecated. So if you are going to use OC4, I suggest to use the new field :-)

**Comment by b-creative** [comment]
That's great, thanks @Timo-Breumelhof !
