### ISSUE TITLE
OpenExtensions.net Errors

### ISSUE THREAD

**Issue by hismightiness** [sachatrauwaen/OpenContent#56]
If you attempt to visit openextensions.net, you get a 404 error.

If you attempt to visit www.openextensions.net, the page loads, but with errors.  

_Error : /Portals/0/Widgets/Templates/Blog/_Latest.cshtml Error when try to create model (url=http://openxtentions.satrabel.be/DesktopModules/Blog/API/RSS/Get?tabid=108&moduleid=504;dataprovider=RSS;datasource=RssFeed) at Satrabel.OpenBlocks.DataSource.DataSourceUtils.GetModel(Dictionary`2 parameters) at Satrabel.OpenBlocks.Token.WidgetTokenProvider.ExecuteWidget(Dictionary`2 parameters)_

**Comment by hismightiness** [comment]
![image](https://user-images.githubusercontent.com/938023/50183014-c6e1a400-02c5-11e9-8f63-ddf5ccaf819f.png)

**Comment by sachatrauwaen** [comment]
fixed
