### ISSUE TITLE
Documentation: How to add sort functionality?

### ISSUE THREAD

**Issue by hismightiness** [sachatrauwaen/OpenContent#58]
Is there any documentation on how to add sort functionality to an existing template?  I believe that the template I'm currently talking about is based on the Catalog template.

http://www.openextensions.net/templates/open-content/catalog

**Comment by robsiera** [comment]
Yes, here yopu find all the details https://opencontent.readme.io/docs/sorting

**Comment by Timo-Breumelhof** [comment]
FYI, I tend to put the order JS files in templates/_Shared so I can share them with other templates

**Comment by hismightiness** [comment]
What about a drop down list that end-users can use to change the sort on-demand?  I don't think the documentation describes this.

**Comment by Timo-Breumelhof** [comment]
That documentation is about drag and drop, you can see here @ 5:18 https://www.youtube.com/watch?v=Qu7oNP2vn9I AFAIK there's no drop-down list option ATM. But you could create a separate template with only a list of titles and drag and drop and put that on a separate page.

**Comment by hismightiness** [comment]
In a typical listing of "items" on a website, the website visitor could sort them by various attributes.  Using e-commerce as an example, you'd be able to sort the visible items by category, price, rating, etc.  Are you saying that there isn't documentation or template example to provide this kind of user experience to end-users?  If not, do you have any suggestions on where/how I might get started on building that?

**Comment by Timo-Breumelhof** [comment]
You are right. The documentation is about ordering items by admins. If you want order or filter for users, you can use jplist, or another library in combination with a callback (if needed, wich only a few items I usually just render the items and us JS filtering)

**Comment by Timo-Breumelhof** [comment]
I changed the documentation, to state that it's about Editors drag and drop..

**Comment by hismightiness** [comment]
It's actually built-in and I missed it.  🤦‍♂️
