### ISSUE TITLE
Sortindex Order

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#59]
To prevent user need to set the sortorder as order for every module that supports inline drag and drop, make the items sort on the sortindex by default if there's a sortindex field.
(which can then be overridden by adding a custom sort)

**Comment by Timo-Breumelhof** [comment]
Option save Filter data from Edit Raw Data as default values

**Comment by sachatrauwaen** [comment]
filter settings will be saved to filter-data.json

**Comment by Timo-Breumelhof** [comment]
Tested and works a expected, example: https://github.com/40fingers/OpenContent-Demo-Templates/tree/main/06.03-Default-Filter%2BOrder

**Comment by Timo-Breumelhof** [comment]
Fixed in V 04.06.00
