### ISSUE TITLE
"Edit Content" > "Add Content" if multi- item Template

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/OpenContent#62]
When you use a Mulit imte m template, the Edit Content button seems a bit unclear.
I would change it to Add Item when using a Mutli template.
I guess in the action menu Add Item would also be better in the case then Add Content (?)

**Comment by sachatrauwaen** [comment]
fixed in v 4.1

**Comment by Timo-Breumelhof** [comment]
Thanks :-)
