### ISSUE TITLE
Remove ID From Detail View Template

### ISSUE THREAD

**Issue by mikesmeltzer** [sachatrauwaen/OpenContent#66]
When using a template that has a detail view it would be ideal if we could remove the ID from the URL and identify another field as the item identifier to generate a friendlier URL.

I'm under the impression that a URL provider would need to be created and shipped specifically for this within OpenContent.  I am investigating creating one for my one-off solution but it would ideal if this was included within OpenContent by default.

Have other users requested this type of functionality before? Do you think this should be a solution within OpenContent or should it be left to users of the module to supply their own provider? I can see merits in both, let's discuss.

**Comment by sachatrauwaen** [comment]
I'am not sure if you speaking about dnn standard url provider solution or somthing else.

In OpenContent v4 there is a additional dnn install package that deliver the functionality you discribe by implementing dnn url privider extention.

After this installed you can define in the manifest how the url identifier of detail page is composed.
It can be a dedicaded field (even multi language field) or composed by concatanating multiple fields.

**Comment by mikesmeltzer** [comment]
Thanks for the fast response.

It sounds like the functionality in v4 is what I'm looking for. I'm currently on v3.x so I will upgrade and give it a try.

Thanks!
