### ISSUE TITLE
EditState not accessible

### ISSUE THREAD

**Issue by b-creative** [sachatrauwaen/OpenContent#67]
When the list view of the articles template is used, a _'#paging:number=10'_ is added to the URL and causes the  DNN EditState button (bottom left) to loose its toggle functionality.

**Comment by sachatrauwaen** [comment]
Hi,

It's a dnn bug, for witch a create a pull request in dnn.
I think it's integrated in dnn 9.3.
https://github.com/dnnsoftware/Dnn.AdminExperience/issues/56

You can switch it of in the template.js (deeplink = false)
