### ISSUE TITLE
Next page in Paging does not start on top

### ISSUE THREAD

**Issue by b-creative** [sachatrauwaen/OpenContent#70]
Maybe it's by design, but I find it not really userfriendly when using the pager, and one clicks to the next page, the next 3, 5 or 10 articles get loaded without a postback. I understand the absence of the postback, but the fact that the user doesn't know that new articles are loaded...

Is there a fix for this?

**Comment by sachatrauwaen** [comment]
Normally you get feedback on the pager and on the page info like on this exemple :

http://www.openextensions.net/demos/opencontent/client-side-catalog

In the articles templates some info can be activated in the settings.

**Comment by b-creative** [comment]
Tnx, I'm aware of the info (Items per page, Current page label, etc) that can be activated, but I'm looking for a way to start from the top again...

**Comment by b-creative** [comment]
Het toevoegen van `data-control-animate-to-top="true"` aan de `ul class="pagination"` werkt.

**Comment by sachatrauwaen** [comment]
Nice !
