### ISSUE TITLE
Filter Settings via Title not always working

### ISSUE THREAD

**Issue by b-creative** [sachatrauwaen/OpenContent#75]
Template Articles; how does the Filter Settings work? It seems that Filter Settings, Filter via Title of an article doesn't always work... Can someone reproduce?

**Comment by sachatrauwaen** [comment]
Can you give an exemple that dousn't work for you ?

Search on text fields use full text search (by terms)!

**Comment by sachatrauwaen** [comment]
After making changes to fields, you need to reindex module in filter settings to rebuild index for search.

**Comment by b-creative** [comment]
Changes like field names? Or also content?

**Comment by b-creative** [comment]
I'm trying to load 1 article on a page. The source of the article is on another page. The source module has 30+ articles with different categories. Whats the best way to filter out 1 particular article? Filtering on a title results in loading the wrong article (with 1 of the 4 searched words in the title)

**Comment by sachatrauwaen** [comment]
You can use some unique identifier on the article like a slug. 
And filter on that
