### ISSUE TITLE
Rightclick on CKeditor gives error

### ISSUE THREAD

**Issue by b-creative** [sachatrauwaen/OpenContent#76]
When I rightclick within my CK editor (for pasting or wanting to check my table settings) I get this error:

![image](https://user-images.githubusercontent.com/8297039/57871287-463dba00-7809-11e9-8bd0-a1ee17493d87.png)

The result is that I do not get a contextmenu

**Comment by b-creative** [comment]
Mmm, my bad; I was still calling the plugin dnnpages, but that isn't very usefull in the OC module...
When deleting this config, the error is gone.

**Comment by sachatrauwaen** [comment]
Fixed in version 1.4.2

**Comment by Timo-Breumelhof** [comment]
4.2 I think :-) ?
