### ISSUE TITLE
Form builder cannot expand fields

### ISSUE THREAD

**Issue by aldeng11** [sachatrauwaen/OpenContent#77]
All browsers.

Use form builder.  Try to expand field in accordion.  Accordion opens briefly and closes.

Release 4.2
![image](https://user-images.githubusercontent.com/27434298/58970525-76280f80-876e-11e9-9f88-55a9af44f7b6.png)

**Comment by aldeng11** [comment]
This is a blocking issue.  The form builder is not usable on release 4.2.

**Comment by sachatrauwaen** [comment]
I can not reproduce on a fresh dnn 9.3.2

Can you describe the steps to reproduce ?

Do you get errors in the browser console ?

**Comment by aldeng11** [comment]
Sacha, I have recorded a screencast to show error.

https://vimeo.com/user7436911/review/341559559/0be237a2f3

Alden Gannon
Six Fish, LLC
206.201.2566
On 6/11/2019 4:51:29 AM, Sacha <notifications@github.com> wrote:
I can not reproduce on a fresh dnn 9.3.2
Can you describe the steps to reproduce ?
Do you get errors in the browser console ?

**Comment by sachatrauwaen** [comment]
The link with the video is not working.

Can you describe the steps to reproduce on a new install ?
Do you get errors in the browser console ?

**Comment by sachatrauwaen** [comment]
Can you try in browser private mode (without chrome plugins enabled).
Or can you send me a host access to sachatrauwaen[at]yahoo.com then i have a look.

**Comment by aldeng11** [comment]
Issue was caused by including bootstrap when skin already did.  Unchecked include bootstrap in general settings and it's fixed
