### ISSUE TITLE
Installation missing glyphs

### ISSUE THREAD

**Issue by aldeng11** [sachatrauwaen/OpenContent#78]
<img width="729" alt="Capture" src="https://user-images.githubusercontent.com/27434298/59308993-505fa680-8c57-11e9-83bd-92a386a32f1a.PNG">
After upgrade to v4.2, missing glyphs in form builder.  Also bad formatting -- running off screen at right.

**Comment by sachatrauwaen** [comment]
as you using bootstrap 4 in edit skin, you need to check load glyphicons in opencontent global settings

**Comment by aldeng11** [comment]
This did the trick for the glyphicons.  Layout issues remain.

**Comment by sachatrauwaen** [comment]
If you get me a host account i will have a look
