### ISSUE TITLE
imgaex: Check for Empty Image Issue

### ISSUE THREAD

**Issue by cklenk** [sachatrauwaen/OpenContent#82]
Hello,

I have a imagex field type. I have not marked as required. In my handlebar file I want to check if it's empty and not display it. I thought I could do the same as any other handle bar if check. See my example:

`{{#if Image}}<img class="img-fluid staff-img" src="{{Image.cropUrl}}" alt="{{Name}}" title="{{Name}}">{{/if}}`

However, it still shows on the dom with a broken image link.

![image](https://user-images.githubusercontent.com/12185742/60297925-50b69d80-98f7-11e9-8e36-f6e4b4dae62b.png)

Is there another way to check for an empty image without doing javascript? All the other field types behave correctly (text area, text, etc).

Thanks

**Comment by Timo-Breumelhof** [comment]
If you checkout the raw data Image probably does exist, but has no cropUrl, so it's better to use:
{{#if Image.cropUrl}} if that's what you want to render.

**Comment by cklenk** [comment]
Thank you, yes that works!
