### ISSUE TITLE
4.2 Issues with imagex filed type

### ISSUE THREAD

**Issue by cklenk** [sachatrauwaen/OpenContent#84]
Has anyone had issues where the crop image button will randomly disappear? It usually comes back after I go into the form builder and hit save again. It's very odd and can't find a consistent pattern on what causes it. I'm happy to share my template files if need be!

Thanks

**Comment by Timo-Breumelhof** [comment]
I have not seen that.
What image field are you using

**Comment by Timo-Breumelhof** [comment]
Oh wait imagex, I see in the title ..

**Comment by Timo-Breumelhof** [comment]
BTW, did you check the schema and options files when you have this issue?
Also, when you go to the field in the editor, is the crop button off?

**Comment by cklenk** [comment]
Yes imagex. This is what the form builder shows:

![image](https://user-images.githubusercontent.com/12185742/61225576-dbb4d780-a6ee-11e9-95e8-83a285e89837.png)

I have type string in my schema.json and in my options and builder.json I have imagex for the type.

**Comment by sachatrauwaen** [comment]
Do you have javascript errors in the browser console ?

**Comment by cklenk** [comment]
/DesktopModules/OpenContent/js/bootstrap/fonts/glyphicons-halflings-regular.woff2 net::ERR_ABORTED 404 (Not Found)
