### ISSUE TITLE
Support for Multiple GitHub Repositories

### ISSUE THREAD

**Issue by hismightiness** [sachatrauwaen/OpenContent#89]
Right now, the default behavior of OpenContent comes pre-configured with the GitHub repository of the "official" templates, below.

https://github.com/sachatrauwaen/OpenContent-Templates

It's currently not possible to point this setting at another repository source, without also ignoring this original repository.  

This update proposes that this setting may contain one or many repositories as a comma-separated listing.  For example:

`sachatrauwaen/OpenContent-Templates,janeDough/Templates,userAccount2/OCTemplates`

When viewing the set-up information that's displayed when first adding the OpenContent module to the page, the drop down list would include the templates from each of the configured template repository sources.  

There's potential for naming conflicts or ambiguity, so the module should prefix the template name with the source in the drop down list, but only if there is more than one source configured.

| Template |
|---|
| janeDough - Articles  |
| janeDough - Accordion  |
| sachatrauwaen - Accordion  |
| sachatrauwaen - Catalog  |
| userAccount2 - Blog  |
| userAccount2 - Classifieds  |

**Comment by sachatrauwaen** [comment]
Sound as good addition.

**Comment by sachatrauwaen** [comment]
added to  v 4.3
