### ISSUE TITLE
Image field issues when pasting text from Excel

### ISSUE THREAD

**Issue by jag64551** [sachatrauwaen/OpenContent#96]
This kind of hard to explain, but I'll do my best. We have an Open Content template setup for a staff directory - image, title, name, email address, bio, etc. The image field works fine, however, when pasting in information from an Excel file into the other fields (e.g. phone number), the image field acts up.

In my example, I have 9 entries, and then I'm adding a new entry. I added the image and some other info, and everything was fine. But then I pasted an email address from an Excel file. The entry I'm working on is fine,

![NewEntry](https://user-images.githubusercontent.com/38305233/65334133-d2813480-db8f-11e9-9828-4c53603d0d10.JPG)

but if I scroll up to other entries, the image field has been replaced by the email address of the very first entry in the set.

![ExistingEntryError1](https://user-images.githubusercontent.com/38305233/65334154-d9a84280-db8f-11e9-9364-78d42141af39.JPG)

Most of the entries are doing this, but not all of them. Some of them still have the original image I added. I have no idea what's going on. We are just using text fields for the data, and then an image field of course for the image.

Using DNN 9.3.2 and OpenContent 4.2.

Any thoughts on this? Thank you.

**Comment by Timo-Breumelhof** [comment]
did you find a fix for this

**Comment by cklenk** [comment]
I don't think we did. We just tried to be careful when copy and pasting.

**Comment by Timo-Breumelhof** [comment]
I guess that the reason for this is that when you paste from excel, MS tends not past only the text but also cell info, layout etc. like it does when pasting from Word.
The form probably interprets that as more than just the text itself, I don;t think there's a simple way around that as it's more of a Excel > Alpaca issue.
